---
title: "p8105_hw2_yl4925"
author: "Yiming Li"
date: "10/3/2021"
output: github_document
---

## Problem 1
```{r}
library(tidyverse)
```

```{r}
trash_wheel_df = readxl::read_excel(
  "./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
  sheet = "Mr. Trash Wheel",
  range = "A2:N535") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  filter(dumpster != "Grand Total") %>% 
  mutate(sports_balls = round(sports_balls))
```

```{r}
pre2019 = readxl::read_excel(
  "./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
  sheet = "2019 Precipitation",
  range = "A2:B14"
) %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2019) %>% 
  relocate(year)

pre2018 = readxl::read_excel(
  "./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
  sheet = "2018 Precipitation",
  range = "A2:B14"
) %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2018) %>% 
  relocate(year)
```

```{r}
##month.name is a vector, not function
bind_rows(pre2018, pre2019) %>% 
  mutate(month = month.name[month])
```

```{r}
sum(pull(pre2018, total))
ball_2019 = filter(trash_wheel_df, year == 2019)
median(pull(ball_2019, sports_balls))
```


## Problem 2

```{r}
pols_month = read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(month = month.name[as.integer(month)]) %>% 
  rename(gop = prez_gop, dem = prez_dem) %>% 
  pivot_longer(
    c("gop", "dem"),
    names_to = "president",
    values_to = "logical") %>% 
  filter(logical != 0) %>% 
  select(-day, -logical) 
```

```{r}
snp_raw = read_csv("./data/fivethirtyeight_datasets/snp.csv") %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(month = month.name[as.integer(month)]) %>%
  select(-"day") %>%
  arrange("year", "month")
snp_after_2000 = filter(snp_raw, year <= 15) %>% 
  mutate(year = as.character(as.numeric(year) + 2000))
snp_before_2000 = filter(snp_raw, year >= 50) %>% 
  mutate(year = as.character(as.numeric(year) + 1900))
snp = bind_rows(snp_after_2000, snp_before_2000) %>% 
  relocate(year, month) %>% 
  arrange(year, month)
```

```{r}
unemployment = read_csv("./data/fivethirtyeight_datasets/unemployment.csv") %>% 
  pivot_longer(
    Jan:Dec, 
    names_to = "month",
    values_to = "unemployment"
  ) %>% 
  mutate(month = month.name[match(month,month.abb)])
```

```{r}
pols_snp = left_join(pols_month, snp) 
pols_snp_unemployment = left_join(pols_snp, unemployment)
```

## Problem 3
```{r}
## 2012是bug的一年，名字和缩写都不对
pop_baby_name = read_csv("./data/Popular_Baby_Names.csv") %>% 
  janitor::clean_names() %>% 
  mutate(ethnicity = recode(ethnicity, "ASIAN AND PACI" = "ASIAN AND PACIFIC ISLANDER",
                            "BLACK NON HISP" = "BLACK NON HISPANIC",
                            "WHITE NON HISP" = "WHITE NON HISPANIC"),
         childs_first_name = str_to_sentence(childs_first_name),
         gender = str_to_sentence(gender),
         ethnicity = str_to_sentence(ethnicity))
```

```{r}
duplictaed_ones = pop_baby_name[duplicated(pop_baby_name[,1:4]),]
distinct_pop_name = pop_baby_name[!duplicated(pop_baby_name[,1:4]),]
```

```{r}
Olivia_female_rank = filter(distinct_pop_name, gender == "Female" & childs_first_name == "Olivia") %>% 
  select(-gender, -childs_first_name, -count) %>% 
  pivot_wider(
    names_from = year_of_birth,
    values_from = rank
  )
```

```{r}
most_popular_male_name = filter(distinct_pop_name, gender == "Male" & rank == 1) %>% 
  select(-gender, -rank, -count) %>% 
  pivot_wider(
    names_from = year_of_birth,
    values_from = childs_first_name
  )
```

```{r}
male_nonhisp_2016 = filter(distinct_pop_name, gender == "Male", 
                           ethnicity == "White non hispanic", 
                           year_of_birth == 2016)
##library(ggrepel)
ggplot(male_nonhisp_2016, aes(x = rank, y = count)) + geom_point() 
##+ geom_text_repel(aes(x = rank, y = count, label = childs_first_name))
```

